### ISSUE TITLE
How to generate GENESIS_TX and GENESIS_NONCE?

### ISSUE THREAD

**Issue by 15963** [sumoprojects/sumokoin#100]
How to generate GENESIS_TX and GENESIS_NONCE?

demo:
std::string const GENESIS_TX = "013c01ff0001ffffffffffff0302df5d56da0c7d643ddd1ce61901c7bdc5fb1738bfe39fbe69c28a3a7032729c0f2101168d0c4ca86fb55a4cf6a36d31431be1c53a3bd7411bb24e8832410289fa6f3b";
uint32_t const GENESIS_NONCE = 10002;

Thank you for any help！！

**Comment by Ingerulro** [comment]
This is sumokoins issue tracker, not for that sort of things. Contact me via telegram: https://web.telegram.org/#/im?p=@Elektryon and we will talk more about your genesis.
