### ISSUE TITLE
Build error: use of undeclared identifier 'aligned_alloc'

### ISSUE THREAD

**Issue by OrchidVC** [sumoprojects/sumokoin#101]
Os environment:
- Macos 10.13
- gcc version:
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Error when compile from source:
/Users/xxx/Downloads/Sumo/sumokoin/src/crypto/cn_slow_hash.hpp:124:18: error: use of undeclared identifier 'aligned_alloc'
                lpad.as_void = aligned_alloc(4096, MEMORY);
                               ^
/Users/xxx/Downloads/Sumo/sumokoin/src/crypto/cn_slow_hash.hpp:125:18: error: use of undeclared identifier 'aligned_alloc'
                spad.as_void = aligned_alloc(4096, 4096);

**Comment by sumogr** [comment]
Compiling if i am not mistaken requires GCC >= 5.0, install it please and try again

**Comment by OrchidVC** [comment]
Gcc version: gcc 7.3.0_1 already installed
But when compile on MacOs, it uses header of /usr/include/c++/4.2.1 (clang LLVM compiler)
I think on macos need change "aligned_alloc" to "posix_memalign"

**Comment by sumogr** [comment]
Ok @curie-kief will check it, i ve already informed him about it, and fix it. Thanks!

**Comment by sumoprojects** [comment]
-- Resolved
