### ISSUE TITLE
Cannot sync with the blockchain

### ISSUE THREAD

**Issue by tianna1121** [sumoprojects/sumokoin#109]
Hi, all

My pool has updated to the latest release now. However, the daemon cannot sync with the blockchain. It complains "DNS seed node lookup either timed out or failed, falling back to defaults"

Any suggestions? Thanks!

ps: my server is located in China. I can ping the added node IP, as follows:

ping 46.105.92.108
PING 46.105.92.108 (46.105.92.108) 56(84) bytes of data.
64 bytes from 46.105.92.108: icmp_seq=1 ttl=44 time=215 ms
64 bytes from 46.105.92.108: icmp_seq=2 ttl=44 time=213 ms
64 bytes from 46.105.92.108: icmp_seq=3 ttl=44 time=214 ms

**Comment by sumogr** [comment]
Most likely it is a corrupt database 
Delete lmdb folder and reimport it or redownload it from scratch.

**Comment by droidcoinio** [comment]
Hi, sumogr

I've deleted ~/.sumokoin and resync from start. Hv, I still got this error...

**Comment by quangvu3** [comment]
> "DNS seed node lookup either timed out or failed, falling back to defaults"

This is a harmless warning, nothing wrong with network, default seed nodes should work but we'll never know what Great Firewall to do with traffic

**Comment by Janjanjanjajaja** [comment]
Hey guys, my sumokoin folder does not show a p2pbin file and an IMDB file. Is there anything else i could try to get the wallet to sync again? Ps: I am not a programmer obviously. Appreciate the help,

**Comment by sumoprojects** [comment]
-- Resolved
