### ISSUE TITLE
Building with MSYS2 is it irrelevant?

### ISSUE THREAD

**Issue by radbud** [sumoprojects/sumokoin#110]
I have been trying to follow the instructions provided here to sync the blockchain and got superbly well until this point:

**Building**
    Make sure path to MSYS2 installed directory in `Makefile` is correct.
    If you are on a 64-bit system, run:
     ` make release-static-win64`

Here i got stuck. I have never used MSYS so don't know much about it but, i have some experience with Terminal, my bitcoin blockchain is on my linux VBox.

When i run that command i get `make: *** No rule to make target 'release-static-win64'.  Stop.`

I couldn't find the Makefile to make sure the path to MSYS2 is correct. I tried all the searches i could in windows, looked in folders everywhere.But, probably Makefile is created when you run that command.. _sorry, i don't understand this!_

Then i searched for info on the error message and still got no relevant info that i could comprehend.

So then i decided to just download the sumokoin binaries and ran the daemon and it is syncing at the moment.

Can anybody explain the relevance of going through the steps for MSYS2 or is it completely irrelevant? And eitherways what's the deal with Makefile, can somebody please help with the info gap here so that people can figure it out a bit more easily?

Sorry for such a noob question, but it is a bit ambiguous. Thanks for the help, and cheers to the devs!!! I'm so hoepful for Sumo!!!

**Comment by sumogr** [comment]
Screw MSYS2 bypass these and build with mingw64 :P 
Update it the same way as msys2 and use mingw64 directly

**Comment by radbud** [comment]
Thanks @sumogr , i will try that.

But, i still have this question: Why do you even need to do that since, the blockchain syncs if you download the binary and run the daemon? Is it required for mining, i doubt that as well since i have XMR-Stack and it works for Monero..

Apologies, if this comes as a noob question, but an explanation simply doesn't exist.

**Comment by sumogr** [comment]
my dearest of friends. What are you trying to do? dont compile it from source if  you dont know how to do it. Use the binaries and how mining is involved with all that you ve lost me. Please close this issue here and come into telegram to ask for support

**Comment by radbud** [comment]
Thanks @sumogr ! The blockchain is synced and working by just using the binaries and running the daemon.

Issue closed.
