### ISSUE TITLE
My blockchain status says it's 9 days ahead!

### ISSUE THREAD

**Issue by radbud** [sumoprojects/sumokoin#114]
Following is the log from my current blockhain status:

`2018-Apr-14 18:29:53.286299 [P2P5]WARNING: no two valid SumoPulse DNS checkpoint records were received
2018-Apr-14 18:49:58.930700 [P2P1][46.158.217.70:19733 OUT]Sync data returned a new top block candidate: 119934 -> 119936 [Your node is 2 blocks (0 days) behind]
SYNCHRONIZATION started
2018-Apr-14 18:50:11.864513 [P2P5][46.158.217.70:19733 OUT]Synced 119936/119936
2018-Apr-14 18:50:11.865012 [P2P5][46.158.217.70:19733 OUT] SYNCHRONIZED OK
2018-Apr-14 18:58:30.184501 [P2P7][83.250.236.224:19733 OUT]Sync data returned a new top block candidate: 119937 -> 116525 [Your node is 3412 blocks (9 days) ahead]
SYNCHRONIZATION started
2018-Apr-14 19:28:41.890281 [P2P1][83.250.236.224:19733 OUT]Sync data returned a new top block candidate: 119945 -> 116525 [Your node is 3420 blocks (9 days) ahead]
SYNCHRONIZATION started
2018-Apr-14 19:33:43.348336 [P2P9][46.158.217.70:19733 OUT]Sync data returned a new top block candidate: 119945 -> 119946 [Your node is 1 blocks (0 days) behind]
SYNCHRONIZATION started
2018-Apr-14 19:33:56.236086 [P2P9]WARNING: no two valid SumoPulse DNS checkpoint records were received
2018-Apr-14 19:33:57.255790 [P2P9][46.158.217.70:19733 OUT]Synced 119946/119946
2018-Apr-14 19:33:57.256292 [P2P9][46.158.217.70:19733 OUT] SYNCHRONIZED OK
2018-Apr-14 19:41:13.228206 [P2P7][83.250.236.224:19733 OUT]Sync data returned a new top block candidate: 119949 -> 116525 [Your node is 3424 blocks (9 days) ahead]
SYNCHRONIZATION started`

 Does anybody see a problem here?

**Comment by quangvu3** [comment]
Some nodes are still at old chain after the fork. No true issues here, old nodes would be banned after a while

**Comment by screab-idh** [comment]
I am getting the same messages with 30+ days ahead. Is this still normal ? My node is running the 3.1.0 version.

**Comment by screab-idh** [comment]
I deleted the blockchain and after a full resync I still get this :

`2018-May-08 12:51:13.710970 [P2P9][37.146.109.225:59968 INC]Sync data returned a new top block candidate: 128250 -> 116525 [Your node is 11725 blocks (32 days) ahead]`

Can you explain to me why this is not a problem ?

**Comment by quangvu3** [comment]
It's not a problem. There are some nodes stuck with old chain (before hardfork) and they stopped at block height# 116525. You node is ahead them bz you are at right blockchain.

**Comment by radbud** [comment]
Agreed. That was sorted.
