### ISSUE TITLE
SumoKoin stuck sync at 117178

### ISSUE THREAD

**Issue by KhmerRun** [sumoprojects/sumokoin#126]
Hello,

The sync of daemon stuck at that height:

2018-Apr-28 20:08:06.740717 [P2P7][92.76.154.150:35075 INC]Sync data returned a new top block candidate: 117178 -> 124798 [Your node is 7620 blocks (21 days) behind]
SYNCHRONIZATION started
2018-Apr-28 20:13:33.315847 [P2P0][49.207.72.106:45782 INC]Sync data returned a new top block candidate: 117178 -> 116525 [Your node is 653 blocks (1 days) ahead]
SYNCHRONIZATION started
2018-Apr-28 20:16:05.468640 [P2P2][92.76.154.150:30648 INC]Sync data returned a new top block candidate: 117178 -> 124800 [Your node is 7622 blocks (21 days) behind]
SYNCHRONIZATION started
2018-Apr-28 20:20:32.072279 [P2P6][92.76.154.150:6960 INC]Sync data returned a new top block candidate: 117178 -> 124800 [Your node is 7622 blocks (21 days) behind]
SYNCHRONIZATION started
2018-Apr-28 20:22:29.502486 [P2P1][92.76.154.150:44068 INC]Sync data returned a new top block candidate: 117178 -> 124800 [Your node is 7622 blocks (21 days) behind]
SYNCHRONIZATION started

Watching it for hours and still there.

Sumokoin 'Aomori' (v0.3.1.0-release)

**Comment by sumoprojects** [comment]
-- Resolved
