### ISSUE TITLE
Failed to parse transaction from blob

### ISSUE THREAD

**Issue by minerlab** [sumoprojects/sumokoin#134]
2018-Jun-09 15:06:07.110423 [P2P2]ERROR /home/quangvhg/sumokoin-sumoproject/src/cryptonote_core/cryptonote_format_utils.cpp:102 Failed to parse transaction from blob

how to fix this?

**Comment by radbud** [comment]
Yup! Same problem here!

I started my weekly scheduled sync for the blockchain and got the following anomaly:

2018-Jun-11 22:25:44.799110 [P2P9][178.114.251.244:65471 INC]Sync data returned a new top block candidate: 139855 -> 141032 [Your node is 1177 blocks (3 days) behind] SYNCHRONIZATION started 2018-Jun-11 22:25:47.897908 [P2P2]ERROR C:/msys64/home/Admin/sumokoin/src/cryptonote_core/cryptonote_format_utils.cpp:102 Failed to parse transaction from blob 2018-Jun-11 22:25:48.672851 [P2P9][83.59.139.132:55962 INC]Sync data returned a new top block candidate: 139855 -> 143894 [Your node is 4039 blocks (11 days) behind] SYNCHRONIZATION started 2018-Jun-11 22:25:50.438435 [P2P2]ERROR C:/msys64/home/Admin/sumokoin/src/cryptonote_core/cryptonote_format_utils.cpp:102 Failed to parse transaction from blob

That is snippet of the daemon log. It kept repeating this for over an hour from 11days to 3 days while i was away.

It looks like my DB is corrupted. But, this is a strange behavior for db corruption i have come across. Any explanation would be helpful.

And how do we fix this?

Thanks!

**Comment by sumoprojects** [comment]
-- Resolved
