### ISSUE TITLE
potential vulnerability?

### ISSUE THREAD

**Issue by attritionorg** [sumoprojects/sumokoin#138]
https://github.com/VenusADLab/EtherTokens/blob/master/sumocoin/sumocoin.md

Note, I am not the author of that document. They call it 'sumocoin' as does etherscan.io, but after a quick search it seems this may refer to sumokoin? Posting here as an FYI in case it impacts this project.

**Comment by abe91q** [comment]
Sumokoin is not an erc20 token.
