### ISSUE TITLE
Difficulty of block 165000 is calculated incorrectly by the daemon and in the official bootstrap

### ISSUE THREAD

**Issue by cotinco** [sumoprojects/sumokoin#139]
Seems that something wrong has happened with difficulty function around block 165000 (last HF).

When I re-sync blockchain from scratch, the difficulties of blocks are:
164999: 44927972711
165000: 35765249082
165001: 37416546319
When I load it from official bootstrap (https://blockchain.sumokoin.org/blockchain.raw), the difficulties are:
164999: 44927972711
165000: 35765249082
165001: 42069324103
Official pool reports:
164999: 44927972711
165000: 41223255770
165001: 42201075672

The only way I found to be consistent with pools is to cut the blockchain just before block 165000, manually specify this block difficulty in source code and then re-sync blockchain from that point. I don't think that it's how it should be, better to be fixed before it lead to chain split. I am using Ubuntu 16.04 server x64, just in case it depends on that.

**Comment by cotinco** [comment]
Seems that the chain split did happen today (I'm not sure about the exact cause, it may be some other thing) - pool.sumokoin.com and sumo.hashvault.pro are on different chains. Cryptopia supports HashVault (in fact, most pools support HashVault, I did not find any supporting pool.sumokoin.com), not sure about TradeOgre. But better to have somebody who reads issues here in time before it comes too far.

**Comment by sumogr** [comment]
Resolved
