### ISSUE TITLE
can't insert more than +-20 transactions into 1 block

### ISSUE THREAD

**Issue by sumonero** [sumoprojects/sumokoin#140]
<pre>The description is quite complicated: 
0) there is CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE in the code, which is "240 * 1024 // 240kB"
1) there is m_current_block_cumul_sz_limit, which is calculated as 2*median from latest 60 blocks and gets lowered to 2*CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE if was higher
2) in "create_block_template" there is a median_size, which is set to m_current_block_cumul_sz_limit/2 and sent to "fill_block_template"as argument
3) in "fill_block_template" there is total_size, which is increased by transaction size after every added transaction
4) in "fill_block_template" there is max_total_size, which is "2*median_size - CRYPTONOTE_COINBASE_BLOB_RESERVED_SIZE" (CRYPTONOTE_COINBASE_BLOB_RESERVED_SIZE=600)
5) when max_total_size < total_size+current transaction size, transaction is skipped
6) but median_size and total_size go into "get_block_reward" as arguments and for first +-20 transactions they pass condition "total_size < 1.1*median_size", for following transactions not
7) because they don't pass the condition, block_reward is not set to the standard base_reward, but to reward_lo, which is lower
 => that is imho wtf, not correct
8) lower block_reward is returned back to "fill_block_template" and "(new) coinbase < best_coinbase" so this transaction (and also all following with the same procedure) are thrown out
9) so first +-20 transactions are added into the block, but next +-20 are added into the next block instead

I guess the method "get_block_reward" should be fixed so it always returns the same block_reward independent on the transaction count. What was the idea of that (prolly) buggy code?

Or maybe it's a feature that the code only adds up to some fixed amount of transactions, but it can be written much more transparently. In that case, why is the amount of transactions limited?

Or maybe limiting the transactions isn't a feature, but some side effect of limiting the amount of money received from a block. In that case, why is the amount of money received from a block limited? And why does it differ from max_total_size used in "fill_block_template"?</pre>

**Comment by sumogr** [comment]
Invalid
