### ISSUE TITLE
stuck sync at 199856

### ISSUE THREAD

**Issue by technics67** [sumoprojects/sumokoin#147]
2018-Oct-03 19:55:23.037454 [P2P3][68.197.36.7:19733 OUT]Sync data returned a new top block candidate: 199856 -> 144619 [Your node is 55237 blocks (153 days) ahead]

above is a part from the log file. happened before and removing everything about the wallet and reinstalling solved the issue but this time i have done it 3 times and cant continue after 199856...

**Comment by LifeGrid01** [comment]
This exact same issue has been going on with me for months. I have uninstalled, removed files, reinstalled, and it still hangs at 199856.

**Comment by LifeGrid01** [comment]
Any luck resolving this issue yet?

**Comment by Altkointalker** [comment]
Please always check for new releases. Follow Sumoprojects or any other of Sumokoin's social media channels to get news about upcoming forks and new releases. The latest release is [Akita, Point Release 1.1](https://github.com/sumoprojects/sumokoin/releases)

**Comment by sumogr** [comment]
Resolved
