### ISSUE TITLE
logfile conflict when running monero and sumo on the same linux server

### ISSUE THREAD

**Issue by atezerotwo** [sumoprojects/sumokoin#26]
when runnning sumo alongside monero on the same linux server we get the following message when trying to start sumokoind:

`sumokoin/src/daemonizer/posix_fork.cpp:22 Unable to open output file: /tmp/bitmonero.daemon.stdout.stderr `

See pull request #25

**Comment by sumoprojects** [comment]
Thanks for report and PR to fix it
