### ISSUE TITLE
sumo-wallet-rpc: tx verification failed

### ISSUE THREAD

**Issue by MineMoneroPRO** [sumoprojects/sumokoin#27]
Hi Sumokoin Team!

I've faced this issue trying to send payments through sumo-wallet-rpc.
The result is the same on v0.1.2.0 and latest commit builds.

So, first I'm invoking **store** method:
```
{"jsonrpc":"2.0","id":"0","method":"store","params":[]}
```
With the **response**:
```
{"id":"0","jsonrpc":"2.0","result":{}}
```

Then trying to make the **transaction**:
```
{  
   "jsonrpc":"2.0",
   "id":"0",
   "method":"transfer",
   "params":{  
      "destinations":[  
         {  
            "amount":4032000209,
            "address":"ADDRESS_1"
         },
         {  
            "amount":3572000117,
            "address":"ADDRES_2"
         }
      ],
      "priority":0,
      "mixin":12
   }
}
```
And wallet-rpc is **crashing** with:
```
[RPC0]ERROR /usr/local/src/sumokoin/src/wallet/wallet2.cpp:3001 daemon_send_resp.status != CORE_RPC_STATUS_OK. THROW EXCEPTION: error::tx_rejected
[RPC0]/usr/local/src/sumokoin/src/wallet/wallet2.cpp:3001:N5tools5error11tx_rejectedE: transaction was rejected by daemon, status = Failed, tx:
[RPC0]Exception: tools::error::tx_rejected
```
While the sumokoin daemon says (and sometimes it crashes after this):
```
[RPC1]transaction with hash 3456178e90f7768838aff163a2eba7c361f75873bab587fe9b4da75603a6dabc not found in db
[RPC1]Key image already spent in blockchain: d6c8bb6a18ca9de4cc81eebf57c2243c998251604bfbb6f2eb9091a1dce7487b
[RPC1]tx used wrong inputs, rejected
[RPC1]Transaction verification failed: <3456178e90f7768838aff163a2eba7c361f75873bab587fe9b4da75603a6dabc>
[RPC1][on_send_raw_tx]: tx verification failed
```

**Here are the full logs:**
[sumo-wallet-rpc.log](https://paste.fedoraproject.org/paste/d6y9bZKlfaLIkJ6IqWMxtA)
[sumokoind.log](https://paste.fedoraproject.org/paste/lRjzu95XlniSrXDAKKb6hg)

**Here is system environment:**
Ubuntu 16.04.3 LTS
GCC / build-essential / 12.1ubuntu2
CMake / cmake / 3.5.1-1ubuntu3
pkg-config / pkg-config / 0.29.1-0ubuntu1
Boost / libboost-all-dev / 1.58.0.1ubuntu1
BerkeleyDB / libdb{,++}-dev / **NO**
libevent / libevent-dev / 2.0.21-stable-2ubuntu0.16.04.1
libunbound / libunbound-dev / 1.5.8-1ubuntu1
libminiupnpc / libminiupnpc-dev / 1.9.20140610-2ubuntu2.16.04.1
libunwind / libunwind8-dev / 1.1-4.1
ldns / libldns-dev / 1.6.17-8
expat / libexpat1-dev / 2.1.0-7ubuntu0.16.04.3
GTest / libgtest-dev / 1.7.0-4ubuntu1
Doxygen / doxygen / **NO**
Graphviz / graphviz / **NO**

Am I missing something?
Thank you.

**Comment by haruto-tanno** [comment]
Wallet RPC is used extensively at mining pools and GUI wallet to make transactions to single or multiple addresses and it works very well atm.

From the logs you pasted here I can see your tx was rejected due to double spending errors. Please make sure your blockchain is fully synced with network and you may need to re-scan the wallet to get rid of out of date txs.

**Comment by MineMoneroPRO** [comment]
And mining pool is my case, yes.

Sumokoind is absolutely synced. Just rescanned bc. The problem still exists.

Maybe I should collect some more info and logs?

Thank you.

**Comment by haruto-tanno** [comment]
Did you try to restore the wallet from seed words? Just in case the wallet file got corrupted (that happened occasionally)

**Comment by MineMoneroPRO** [comment]
Mm, the output changed after wallet restoration:
`failed to get random outs, status = Too many outs requested`
Request: https://paste.fedoraproject.org/paste/59MG8GoFrd5vQZRbFBV68A
Full wallet-rpc log: https://paste.fedoraproject.org/paste/XoaM00kQb8Jexszr6OpNJA


And then I run it again - and it fails again.
And then I run it third time - and it processed.
Nothing was changed between this runs.

**Comment by haruto-tanno** [comment]
That was rather strange errors. Each time the wallet selected different random outputs for mixins and the last selection appeared to work. Maybe, you need to reduce number of addresses to send to at each transaction to make sure it works all the time.

**Comment by MineMoneroPRO** [comment]
Does 10 recipients look reasonable?

**Comment by haruto-tanno** [comment]
Yes, I think bw 10 to 15 are ok. You can start with less recipients and increase number over the time as long as the wallet works well

**Comment by MineMoneroPRO** [comment]
Thank you!

Quick look at the official pool's payments is showing max 18 recipients. This was adjusted experimentally too?

**Comment by haruto-tanno** [comment]
Yes, we tried different numbers from time to time

**Comment by MineMoneroPRO** [comment]
Should I close the issue?
For me it still looks like something is going wrong.
And this errors should not kill the daemon and wallet-rpc anyway. But they do.

**Comment by haruto-tanno** [comment]
Right, probably the build was not stable though I'm not sure why. Probably, you may try pre-built banaries?

**Comment by MineMoneroPRO** [comment]
I've tried. Result was the same.

**Comment by haruto-tanno** [comment]
So, it's about the overall stability of the software that has issues with serious errors. But this specific case seems solved and you can close the issue now.

**Comment by MineMoneroPRO** [comment]
Thank you once again.

**Comment by MineMoneroPRO** [comment]
Sorry, but I have to disturb you once again.
After long days of testing I'm still getting this last error (Too many outs requested).
Even when I try a single tx.
Maybe you have some more ideas for my case?

**Comment by haruto-tanno** [comment]
Can you please check your system, especially system dare/time to make sure it's synced with global date/time? My guess is the issue could be system-specific as we have no reports of similar issues from other wallets.
