### ISSUE TITLE
Build fails on RPi2

### ISSUE THREAD

**Issue by esfomeado** [sumoprojects/sumokoin#31]
val_secalgo.c:258:8: error: dereferencing pointer to incomplete type DSA_SIG {aka struct DSA_SIG_st}
dsasig->r = R;

val_secalgo.c:291:11: error: dereferencing pointer to incomplete type ECSDA_SIG {aka struct ECDSA_SIG_st}
ecdsa_sig->r = BN_bin2bn(*sig, bnzise, ecdsa_sig->r);

val_secalgo.c:509:13: error: storage size of ctx isn't know
EVP_MD_CTX ctx;

**GCC:** 6.3.0

**Comment by philprobinson84** [comment]
At what point in the instructions do you encounter the error?

I haven't been able to recreate this problem - having followed the instructions in README.md to build and install, my RasPi2 is now syncing with the network.
![rpi2_sumo1](https://user-images.githubusercontent.com/1550779/31849926-6fd69f92-b642-11e7-8c13-ce1e26b34bd9.png)

My install was not completely clean, so I will repeat my test using a completely clean install and make some more detailed instructions in the process.

**Comment by philprobinson84** [comment]
I get the same problem on a clean install of Raspbian Stretch. Stretch has OpenSSL 1.1 whereas Jessie used 1.0, the build fails unless OpenSSL 1.0 is used (see related monero issue: https://github.com/monero-project/monero/issues/1411). Running `sudo apt-get install libssl1.0-dev` switches 1.1 for 1.0 and fixes this. I'll update the instructions and submit a PR shortly.

**Comment by esfomeado** [comment]
I installed later the libunbound and solved the problem.

**Comment by sumoprojects** [comment]
So the issued will be closed
