### ISSUE TITLE
I Can´t do transfers

### ISSUE THREAD

**Issue by sabiron** [sumoprojects/sumokoin#35]
Hi

I have installed the gui wallet 0.0.1 beta 2 on WIn 10 x64

-On 11/4/2017 i made one transfer to Cryptopia.
-The transfer run correctly and was registered in my wallet TX history, but checking on Cryptopia, the 15 SUMO coins dont appear.
-After check on cryptopia i make the folllowing: "rescan spent" + "rescan Blockchain"
-After the rescan the transfer dissapeared from my "TX history"
- if I "rescan spent" the balance updates to: 13.204 sumo. (Before the transfer my balance was 28.424) and if i "rescan the blockchain" one more time the balance comes again to 28.424 Sumo.

After this problems i have try to make transfers to a nwe generated wallet and i get the error "Transaction was rejected by daemon" and if go to the log i get this:

[2017-11-04 23:19:36,875] [INFO] [sumokoind]>>> 2017-Nov-04 23:19:36.876957 [RPC0][on_send_raw_tx]: tx verification failed

**Comment by quangvu3** [comment]
As far as I see, the coins was transferred to Cryptopia already but I guess you'd forgotten to add Payment ID to transaction. If so, please contact Cryptopia support with transaction id for help.
