### ISSUE TITLE
Exception: cryptonote::TX_DNE

### ISSUE THREAD

**Issue by Spinaker70** [sumoprojects/sumokoin#40]
I see a lot of `Exception: cryptonote::TX_DNE Unwound call stack:` in my sumokoin.log when i use sumo-wallet-cli.
[sumokoin.log](https://github.com/sumoprojects/sumokoin/files/1525681/sumokoin.log)

```
./sumokoind --version
Creating the logger system
Sumokoin 'Sapporo' (v0.2.0.0-release)

./sumokoind --os-version
Creating the logger system
OS: Linux #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 4.10.0-40-generic
```

**Comment by haruto-tanno** [comment]
Did you download pre-built binaries or compile them?

**Comment by Spinaker70** [comment]
Binaries from https://github.com/sumoprojects/sumokoin/releases/download/v0.2.0.0/sumokoin.linux.x64.v0-2-0.tar.bz2

**Comment by haruto-tanno** [comment]
So, is syncing ok or had any issue beside the exception stack in log file?

**Comment by Spinaker70** [comment]
```
[wallet/0 Sumoo1ssR]: status
Refreshed 76673/76673, synced, daemon RPC v1.0
```
but
```
[wallet/0 Sumoo1ssR]: show_transfers
[wallet/0 Sumoo1ssR]: 

```

**Comment by haruto-tanno** [comment]
If you are using old wallet files, pls run `rescan_bc` to see old tx history

**Comment by Spinaker70** [comment]
After `rescan_bc` log file is clean. Solved. Thnx!

**Comment by Spinaker70** [comment]
I launched `rescan_bc` and now I see  old tx history.
But this did not fix error :(

**Comment by sumoprojects** [comment]
Resolved
