### ISSUE TITLE
New difficulty algorithm

### ISSUE THREAD

**Issue by zawy12** [sumoprojects/sumokoin#41]
If you ever need to fork, here's a [much better difficulty algorithm](https://github.com/zawy12/difficulty-algorithms/issues/4). This might be the best there is.  If I find something better, [I'll post it here](http://zawy1.blogspot.com/2017/11/best-difficulty-algorithms.html).

**Comment by haruto-tanno** [comment]
Thanks @zawy12 I'll see if that'll be good solution (at least on lab). Currently, we are quite happy with the last algo (though it's not perfect) to find botnets, surge hashrate etc.

**Comment by zawy12** [comment]
I keep the newest version of the algorithm [here.](https://github.com/zawy12/difficulty-algorithms/issues/4)

Masari copied your algo and had a lot of problems.  They've done awesome with the WHM I helped devise and I'm getting them to go to EMA in their next fork.  

The following shows your history compared to other coins, and how Masari is doing a lot better.

https://github.com/zawy12/difficulty-algorithms/issues/6

**Comment by zawy12** [comment]
There was an error in the way I was handling timestamps that's been corrected in the links.

**Comment by zawy12** [comment]
We've developed a new algorithm that's the best of the best and allows integer math on the target.

https://github.com/zawy12/difficulty-algorithms/issues/17

**Comment by screab-idh** [comment]
Wouldn't this stay better in a pull request ?

**Comment by zawy12** [comment]
I don't have completed code for pull requests.  

The algorithm that works the best is the [LWMA aka WHM](https://github.com/zawy12/difficulty-algorithms/issues/3).  Bitcoin gold is going to use it and they posted python code for it in the comments. They also found an error that's been corrected.

**Comment by zawy12** [comment]
[Here's live data on 5 monero clones using LWMA](https://github.com/zawy12/difficulty-algorithms/issues/23)

**Comment by zawy12** [comment]
Here's karbowanec's results after switching from an SMA N=17 like Sumokoin's to the new LWMA.  Sumokoin is the only coin remaining (that I am aware of) that isn't about to upgrade from N=17 to the new one.  Forknote will upgrade so that new coins created via forknote will not have the problem.

The N=17 was really fast, but it caused way too many problems due to varying up and down too much, inviting miners to constantly engage in on-off mining which you can easily see as the oscillations.  The new N with LWMA is chosen to be as fast as possible without inviting these on-off attacks with accidentally low difficulty.

The chart shows a long timestamp manipulation attack before the switch to LWMA occurred.
![karb_lwma](https://user-images.githubusercontent.com/18004719/38498808-92a8d384-3bd3-11e8-8f68-e5c540e6752d.gif)

**Comment by zawy12** [comment]
All of the coins who copied Sumo's difficulty algorithm are experiencing an attack like the following.  It is not merely a hash attack like Sumo recently had, but they are included bad timestamps.  Likewise, Sumo's code has the vulnerability that is caused by Future_time_limit set to 7200 instead of 500 and because there is a sort of the timestamps before the difficulty is calculated.  This causes the difficulty to drop up to 30% per block until it is zero.  It only takes a 20% hash rate miner to perform the attack, so POW does not provide protection.  Most of the coins that had Sumo's code have upgraded even without changing the POW to stop the attacks.  

IntenseCoin will have to revert the chain 5,000 blocks or more and fork. 

![image](https://user-images.githubusercontent.com/18004719/38845862-7dee20f8-41c7-11e8-84a1-1a1fa895abb7.png)

**Comment by zawy12** [comment]
[17 times I warned Sumo last year](https://github.com/sumoprojects/sumokoin/pull/10) when we developed the algorithm that they really really needed to allow negative solvetimes (instead of sorting them).

**Comment by quangvu3** [comment]
Simply copying the code without knowing the inside settings is problem. You cannot attack Sumo by timestamp (unless you have 80% or more hashpower and very accurately) bz Sumo allows only 30 min ahead (not behind) and any wrong timestamp forward would be neutralized by next correct block due to internal sort.

**Comment by zawy12** [comment]
30 minutes ahead of previous block? That's not real protection with the future_time_limit still set to 7200 if the attacker is > 50%.  Since  BLOCKCHAIN_TIMESTAMP_CHECK_WINDOW is still 60, if they haven't also limited reverse times like I recommended last summer, all an attacker needs to do is send -30x240 timestamps once every 3 blocks and difficulty will go to zero shortly... which is a direct result of using the sort.

**Comment by quangvu3** [comment]
Oh, you saw wrong places, Sumokoin uses these:

```
#define CRYPTONOTE_BLOCK_FUTURE_TIME_LIMIT_V2           60*24
#define BLOCKCHAIN_TIMESTAMP_CHECK_WINDOW_V2            12
```

Actually, you can set ahead 24 mins only and pls note that 6 first blocks (equal to 24 mins block time) are always cut from diff calculation, so to successfully attack timestamp you'll need to sneak into full 6 blocks with forward timestamp. As discussed before, it'll be very tough job even IF you have majority of hashpower.

> 30 minutes ahead of previous block?
No, 30 mins from current (server) time, it makes the job much tougher

And that's why, through many kinds of attacks, the algo is standing. I don't say it's perfect but it has no major flaws for sumokoin. Copying code won't work unless they have the same settings, the same blocktime etc.

**Comment by zawy12** [comment]
Oh, sorry, I was mistaken. That should be good protection from bad timestamps.

**Comment by sumoprojects** [comment]
-- Resolved
