### ISSUE TITLE
Subaddresses vanish after rescan_bc

### ISSUE THREAD

**Issue by SadBatman** [sumoprojects/sumokoin#42]
When you run rescan_bc you will lose the subaddresses.  
You can see this in action below:

```
[wallet/0 Sumoo4yWx]: address new aloha
1  SuboQMHp8bocF86Xe9CHu4Gtkq5GbJvH9MbvfEqc3c5EcHYpgKJHUQUFNDnKbrL3kqa2cTc481F9WXZsiMh9kd7J5mwh2XzZmT  aloha 
[wallet/0 Sumoo4yWx]: address all
0  Sumoo4yWxpb88LRhrtZ4z2YKymG8nTnfnYPD65GcDmzZASWM4ohVUS1gTMe2cxrhDNTtqx41ULwsLNdF1z9YxAwvZEscipJTwCv  Primary address 
1  SuboQMHp8bocF86Xe9CHu4Gtkq5GbJvH9MbvfEqc3c5EcHYpgKJHUQUFNDnKbrL3kqa2cTc481F9WXZsiMh9kd7J5mwh2XzZmT  aloha 
[wallet/0 Sumoo4yWx]: rescan_bc
Starting refresh...
Refresh done, blocks received: 11                               
Currently selected account: [0] Primary account
Balance: 0.000000000, unlocked balance: 0.000000000
[wallet/0 Sumoo4yWx]: address all
0  Sumoo4yWxpb88LRhrtZ4z2YKymG8nTnfnYPD65GcDmzZASWM4ohVUS1gTMe2cxrhDNTtqx41ULwsLNdF1z9YxAwvZEscipJTwCv  Primary address 
[wallet/0 Sumoo4yWx]: 
```

**Comment by quangvu3** [comment]
Subaddresses are not automatically re-generated after `rescan_bc` (which basically reset the whole wallet). Subaddresses are only re-generated after rescanning or restoring from seed words if they had in/out txs already

**Comment by SadBatman** [comment]
Thanks for explaining.  A small suggestion: maybe it's worth to add a warning to rescan_bc that any subaddresses without transactions will be gone ? 

In my case I was testing using testnet.  On my testnet I run a miner with a subaddress and it has not earned any coins yet.  I ran rescan_bc and my wallet no longer displays the subaddress.

If the miner is rewarded; will the reward still show up in the wallet ? Will the wallet then also automatically add the subaddress to it's list ? (e.g. because there was a transaction)

**Comment by quangvu3** [comment]
Can you pls close this issue @SadBatman?
