### ISSUE TITLE
Home dir under linux?

### ISSUE THREAD

**Issue by buterrip69** [sumoprojects/sumokoin#43]
Hello, i'm using the precompiled version for ubuntu in debian.
So i'm using this on an external device, which is mounth in /media/blabla/ and the wallets are in /media/blabla/wallets. So each time i open a wallet, the ./wallet script keeps creating them in /home/user which i would not lile to happen.
Is there a way to specify to the ./wallet the home directory as /media/blabla/wallets?
Thanks guys

**Comment by buterrip69** [comment]
Other than that a good solution for this behavior would be to put the wallet directory inside of the wallet itself, that way there would not be this problem i believe?

**Comment by marcopolo88** [comment]
I second that: having the blockchain data lmdb on usb or flash card creates a overwhelming io load.  being able to customize the datadir on emmc/sata is essential.
using precompiled arm7 release sapporo

**Comment by marcopolo88** [comment]
so
the --data-dir location option is indeed supported. sumokoind help did not show this command, as it is an option entity
run
./sumokoind --data-dir="path"

**Comment by marcopolo88** [comment]
please close here
