### ISSUE TITLE
Despite running the latest version, daemon tells me that I need to update

### ISSUE THREAD

**Issue by alikuru** [sumoprojects/sumokoin#45]
I have compiled the Sumokoin from the latest Github release tag [v0.2.0.0](https://github.com/sumoprojects/sumokoin/releases/tag/v0.2.0.0) and synchronized. Daemon immediately started show this message in red after synchronization finished:

```
Last scheduled hard fork time shows a daemon update is needed now.
```

When I check status, I see this:

```
Height: 82287/82287 (100.0%) on mainnet, not mining, net hash 6.50 MH/s, v2, update needed, 8+0 connections
```

Is there a newer version available? If there is, where can I get it?

**Comment by TheTimeWalker** [comment]
This is just leftover code from when it spun off of Monero as that one has planned hard forks every six months. You can safely ignore it until that relevant part in the code has been removed

**Comment by alikuru** [comment]
Thanks for the information, closing.
