### ISSUE TITLE
Improve wallet API transaction error codes

### ISSUE THREAD

**Issue by mrheinen** [sumoprojects/sumokoin#53]
The wallet API currently returns 3 different status codes:
```
      enum Status {                                                                
          Status_Ok,                                                               
          Status_Error,                                                            
          Status_Critical                                                          
      };   
```
This makes it very difficult for API users to understand what actually happened when a transaction cannot be executed. E.g. in the android wallet we can only tell the user that "The transaction failed" whereas it would be cooler if the API could return a Status_Insufficient_Funds so that we can provide more specific feedback to the user (or solve the issue in code).

Hope this makes sense.  I'm happy to take this issue ;)

**Comment by haruto-tanno** [comment]
That makes sense @SadBatman. You are welcome to contribute code ofc :)

**Comment by anthonydotnet** [comment]
@SadBatman If you could name some status codes that you think are useful, then maybe that will encourage someone to pick up this issue.

**Comment by sumoprojects** [comment]
-- Resolved, more infomative msg returned now
