### ISSUE TITLE
Genesis

### ISSUE THREAD

**Issue by SpliffyMap** [sumoprojects/sumokoin#56]
Hello. How did you generated genesis block??

**Comment by wildnrg** [comment]
I would also like to know too.

Someone else posted the following on stackexchange but I don't know what to substitute in the transaction pubkey field and output fields

version
01
unlock time (varint, height, 60 here)
3c
vin length (value in)
01
vin #1 (of 1) type (gen, 0xff)
ff
height for gen input
00
vout length (value out)
01
output #1 (of 1) amount (17592186044415 as varint)
ffffffffffff03
output #1 type (to key, 0x02)
02
output #1 key (32 bytes)
9b2e4c0281c0b02e7c53291a94d1d0cbff8883f8024f5142ee494ffbbd088071
extra length in bytes (varint, here 33)
21
extra pubkey tag (0x01)
01
transaction pubkey (32 bytes)
7767aafcde9be00dcfd098715ebcf7f410daebc582fda69d24a28e9d0bc890d1

**Comment by quangvu3** [comment]
Pls post this to some expert forum for help. This is for issue tracking only
