### ISSUE TITLE
Sent From Cryptopia to Sub Address Wallet - Processing

### ISSUE THREAD

**Issue by hashgalore** [sumoprojects/sumokoin#57]
I was messing around with sub addresses, and decided to do a small test of 0.1 Sumo from Cryptopia to my new sub address created via the OS X gui wallet.  I didn't think of checking to see if Cryptopia was on the latest version release and if sub addresses were supported before trying.  

It appears that Cryptopia hasn't implemented the sub addresses release, and my transfer is still in the processing state.  Will this transfer be stuck in limbo until Cryptopia implements the newest release, or is it lost in the black hole?  Just an FYI for anyone else thinking about trying this.

**Comment by quangvu3** [comment]
Subaddress feature has not been supported by Cryptopia as they haven't upgrade to the latest version. Coins won't be lost as the tx would never happen

**Comment by quangvu3** [comment]
FYI, withdrawal to subaddresses are supported by Cryptopia exchange now
