### ISSUE TITLE
[upgrade to GUI]

### ISSUE THREAD

**Issue by kesior** [sumoprojects/sumokoin#61]
Hello! Would it be possible to allow a custom installation path so that the whole wallet+db be put on another drive rather than c:\program data | c:\program files (x86)? Even using the Standalone ZIP, when running the wallet.exe it automagically loads most of the files to the c:\ location.

Thank you.

**Comment by quangvu3** [comment]
Right now the only way is to run daemon separately and use parameter `--data-dir` to point to another location. GUI will just connect to the running daemon when starting.

**Comment by kesior** [comment]
Thank you for your response. Have a nice day!
