### ISSUE TITLE
Error while compiling under Ubuntu 14.04

### ISSUE THREAD

**Issue by Ingerulro** [sumoprojects/sumokoin#64]
/root/work/sumokoin/src/mnemonics/electrum-words.cpp: In function 'words_to_bytes':
/root/work/sumokoin/src/mnemonics/electrum-words.cpp:278:75: warning: 'language' may be used uninitialized in this function [-Wmaybe-uninitialized]
       const std::vector<std::string> &word_list = language->get_word_list();
                                                                           ^
/root/work/sumokoin/src/mnemonics/electrum-words.cpp:273:23: note: 'language' was declared here
       Language::Base *language;
                       ^
/tmp/ccYqXL4e.ltrans16.ltrans.o: In function `tools::wallet2::load(std::string const&, std::string const&)':
<artificial>:(.text+0x408f): undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
<artificial>:(.text+0x4b3f): undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status

**Comment by sumoshi** [comment]
What OS you were on while compiling code?

**Comment by quangvu3** [comment]
Did you see any SSL lib related problem?

**Comment by sumoprojects** [comment]
Should be fixed with PR #80
