### ISSUE TITLE
daemon update is needed now

### ISSUE THREAD

**Issue by tjc808** [sumoprojects/sumokoin#69]
2018-Jan-26 00:07:11.232200 [P2P0]WARNING: no two valid SumoPulse DNS checkpoint records were received
2018-Jan-26 01:09:37.192290 [P2P1]WARNING: no two valid SumoPulse DNS checkpoint records were received
2018-Jan-26 02:00:29.600437 [P2P6]
**********************************************************************
Last scheduled hard fork time shows a daemon update is needed now.
**********************************************************************

https://www.reddit.com/r/sumokoin/comments/7kjwv3/last_scheduled_hard_fork_time_shows_a_daemon/

Not an issue for sumo right?

**Comment by 4Reallive** [comment]
Yeah what is going on?
github repo wont compile
binary on website ends up with this?

**Comment by tjc808** [comment]
Im compiling just fine, pool is synced and online.

**Comment by tjc808** [comment]
@4Reallive Ohhhhh ya I haven't tried the new compile yet. Your saying the new sumokoin wallet won't compile for you.

**Comment by tjc808** [comment]
Latest wallet compiled fine and is now syncing.

**Comment by tjc808** [comment]
2018-Feb-01 23:59:54.766240 Blockchain initialized. last block: 0, d2038.h18.m59.s54 time ago, current                              difficulty: 1
2018-Feb-01 23:59:54.766272 Blockchain checkpoints file not found
2018-Feb-01 23:59:54.829773 DNSSEC validation failed for checkpoint update at URL: checkpoints.sumopul                             se.stream, skipping.
2018-Feb-01 23:59:54.835122 DNSSEC validation failed for checkpoint update at URL: checkpoints.sumopul                             se.download, skipping.
2018-Feb-01 23:59:54.846711 DNSSEC validation failed for checkpoint update at URL: checkpoints.sumopul                             se.win, skipping.
2018-Feb-01 23:59:54.857850 DNSSEC validation failed for checkpoint update at URL: checkpoints.sumopul                             se.bid, skipping.
2018-Feb-01 23:59:54.857883 WARNING: no two valid SumoPulse DNS checkpoint records were received
2018-Feb-01 23:59:54.857902 batch transactions not enabled
2018-Feb-01 23:59:54.858042 ERROR /home/ubuntu/sumokoin/src/daemon/daemon.cpp:145 Uncaught exception!                              batch transactions not enabled
2018-Feb-01 23:59:54.858068 Deinitializing rpc server...
info   {1} {p1} 2018-02-01 23:59:54.858119 [connection_basic.cpp+173 ::~connection_basic] Destructing                              connection p2p#0 to 0.0.0.0
2018-Feb-01 23:59:54.858161 Deinitializing p2p...
info   {1} {p1} 2018-02-01 23:59:54.858359 [connection_basic.cpp+173 ::~connection_basic] Destructing                              connection p2p#0 to 0.0.0.0
2018-Feb-01 23:59:54.858392 Deinitializing core...
2018-Feb-01 23:59:54.858412 Miner has received stop signal
2018-Feb-01 23:59:54.858425 Not mining - nothing to stop
2018-Feb-01 23:59:54.858437 Received signal to deactivate memory pool store
2018-Feb-01 23:59:54.858534 Memory pool store deactivated successfully
2018-Feb-01 23:59:54.858552 Stopping blockchain read/write activity
2018-Feb-01 23:59:54.859381 Local blockchain read/write activity stopped successfully
2018-Feb-01 23:59:54.859412 Blockchain directory successfully unlocked
2018-Feb-01 23:59:54.859450 Miner has received stop signal
2018-Feb-01 23:59:54.859466 Not mining - nothing to stop
2018-Feb-01 23:59:54.859520 Stopping cryptonote protocol...
2018-Feb-01 23:59:54.859537 Cryptonote protocol stopped successfully

**Comment by SadBatman** [comment]
"Uncaught exception! batch transactions not enabled"

^^ that is the main issue @sumoshi

**Comment by sumoshi** [comment]
Batch transaction was enabled at the commit https://github.com/sumoprojects/sumokoin/commit/7e81c702bd788ace790e38d63b1a732205ee5d88

> no two valid SumoPulse DNS checkpoint records were received

Sumokoin has mechanism to pull seed nodes from DNS records, yet not enabled at the moment.

> Last scheduled hard fork time shows a daemon update is needed now.

No schedule hardfork planned yet for Sumokoin, the warning message is from Monero code, will be removed at next update.

Thanks you all for reporting
