### ISSUE TITLE
Code stolen from Monero without credit

### ISSUE THREAD

**Issue by stoffu** [sumoprojects/sumokoin#70]
This patch https://github.com/sumoprojects/sumokoin/commit/916e7d5ce67b4023645a7ce3a064142e17038010 is a straight copy of @noahdesu's contribution in https://github.com/monero-project/monero/commit/44a5b03841e34154e824fcc7773c458326a3487f without any credit.

**Comment by heptathlon** [comment]
Another DMCA incoming, copycats.

**Comment by sumoshi** [comment]
While it was Bill's mistake not give the code author credits, all related files had been retained copyright to The Monero Project:

https://github.com/sumoprojects/sumokoin/blob/master/src/daemon/daemon.cpp
https://github.com/sumoprojects/sumokoin/blob/master/src/daemon/daemon.h
https://github.com/sumoprojects/sumokoin/blob/master/src/daemonizer/posix_daemonizer.inl

The docker file, however, has no copyright notice but we don't mind to add it for The Monero Project if required.

The whole project is basically a fork and codes from upstream are everywhere. We've tried to retain all copyrights to The Monero Project to all files we have no actual contributions at the commit:

https://github.com/sumoprojects/sumokoin/commit/70d76e70d581e4fdb75049bd1fd97c26302b9d5c

**Comment by noahdesu** [comment]
IANAL, and I don't have any knowledge of the OSS license that Monero falls under, but in general I would never expect fine-grained acks like this. From my perspective, I contributed to the Monero project, and expect it to fall under that entire licensing umbrella. For the record, no attribution from me is necessary, though I completely support anyone that seeks credit when appropriate.

**Comment by quangvu3** [comment]
Thanks @noahdesu for your stand and sorry for all mistakes about copyright. Sumokoin, itself, has already had some forks and, I guess, will have many more. While copyright and credits are always an issue, we hope we'll never have to use it as an ultimate measure to take down any clone or competitor

**Comment by stoffu** [comment]
I think it's critically important to make a clear distinction between genuinely original new codes and simple merge of Monero's patches; currently Sumokoin, unintentionally or otherwise, is making itself appear to be innovating something technical while it's not in reality. My suggestion for this kind of situation is to simply mention the original PR, like @haruto-tanno did in the subaddresses patch #28.

**Comment by quangvu3** [comment]
It was not simply a patch as Sumokoin code base was at v0.10.1 while the subaddresses codes were for current version of Monero (having enormous diff). AFAIK, Haruto had hard time to incorporate subaddresses to Sumokoin and he did credit author. But you are right if Sumokoin merge other simple patches from upstream code.

**Comment by SadBatman** [comment]
Could someone tell me whether this also a correct solution:

Since the code was contributed to the Monero project initially; the sumokoin files to which the code was added should be updated and their Monero copyright line should be updated to contain 2018.
