### ISSUE TITLE
Compiling issues "wallet2"

### ISSUE THREAD

**Issue by tjc808** [sumoprojects/sumokoin#71]
Hello,

Is there something that needs to be done to compile the new code...or are the changes a delay to avoid the monero conflict? 

2018-Jan-31 23:08:32.884952 Sumokoin 'Sapporo' (v0.2.0.0-be01bb6)
2018-Jan-31 23:08:32.885252 Setting log level = 0
2018-Jan-31 23:08:32.885363 default_log: ./sumo-wallet-rpc.log
2018-Jan-31 23:08:32.885480 Logging at log level 0 to /home/ubuntu/sumokoin/build/release/bin/./sumo-wallet-rpc.log
2018-Jan-31 23:08:32.885810 Loading wallet...
2018-Jan-31 23:08:32.932777 Loaded wallet keys file, with public address: Sumoo"address removed"
2018-Jan-31 23:08:33.033588 ERROR /home/ubuntu/sumokoin/src/wallet/wallet2.cpp:1320 !r. THROW EXCEPTION: error::no_connection_to_daemon
2018-Jan-31 23:08:33.034845 /home/ubuntu/sumokoin/src/wallet/wallet2.cpp:1320:N5tools5error23no_connection_to_daemonE: no connection to daemon, request = gethashes.bin
2018-Jan-31 23:08:33.035904 ERROR /home/ubuntu/sumokoin/src/wallet/wallet_rpc_server.cpp:1635 Wallet initialization failed: no connection to daemon

Thanks Sumo Dev.

**Comment by tjc808** [comment]
HOMIES i got you soon...

**Comment by tjc808** [comment]
what changes where amde to the core_rpc_server.h

**Comment by tjc808** [comment]
not seeing this anymore with fresh code download.

**Comment by haruto-tanno** [comment]
+ can be closed
