### ISSUE TITLE
notify#1 build issue

### ISSUE THREAD

**Issue by tjc808** [sumoprojects/sumokoin#72]
/home/ubuntu/sumokoin/src/mnemonics/electrum-words.cpp:279:75: warning: ‘language’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       const std::vector<std::string> &word_list = language->get_word_list();
                                                                           ^
/home/ubuntu/sumokoin/src/mnemonics/electrum-words.cpp:274:23: note: ‘language’ was declared here
       Language::Base *language;
                       ^
/usr/bin/ld: /tmp/ccyALe6y.ltrans16.ltrans.o: undefined reference to symbol 'SSL_get_verify_callback@@OPENSSL_1.0.0'
//lib/x86_64-linux-gnu/libssl.so.1.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/wallet/CMakeFiles/wallet_rpc_server.dir/build.make:127: recipe for target 'bin/sumo-wallet-rpc' failed
make[3]: *** [bin/sumo-wallet-rpc] Error 1
make[3]: Leaving directory '/home/ubuntu/sumokoin/build/release'
CMakeFiles/Makefile2:1189: recipe for target 'src/wallet/CMakeFiles/wallet_rpc_server.dir/all' failed
make[2]: *** [src/wallet/CMakeFiles/wallet_rpc_server.dir/all] Error 2
make[2]: Leaving directory '/home/ubuntu/sumokoin/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ubuntu/sumokoin/build/release'
Makefile:43: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by tjc808** [comment]
This was likely due to apt-get upgrade on ubuntu 16.04LTS, Brand New AWS instance. The issues is not present now.

**Comment by tjc808** [comment]
This was more a notification to remove the reference to electrum.

**Comment by Warlordas** [comment]
I'm having the same issue on ubuntu 16.04LTS
/usr/bin/ld: /tmp/ccQOIved.ltrans18.ltrans.o: undefined reference to symbol 'SSL_get_verify_callback@@OPENSSL_1.0.0'
//lib/x86_64-linux-gnu/libssl.so.1.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/wallet/CMakeFiles/wallet_rpc_server.dir/build.make:127: recipe for target 'bin/sumo-wallet-rpc' failed
make[3]: *** [bin/sumo-wallet-rpc] Error 1

**Comment by jpenner123** [comment]
Workaround:

try 
make release-static

Worked for me...

**Comment by haruto-tanno** [comment]
Fixed by https://github.com/sumoprojects/sumokoin/pull/80

**Comment by sumoprojects** [comment]
Fixed, closed
