### ISSUE TITLE
Segmentation fault when sending sumo

### ISSUE THREAD

**Issue by screab-idh** [sumoprojects/sumokoin#74]
Hi,

I tried to transfer some sumo to another address and this is what I get:

```bash
user@machine:~/crypto/sumokoin$ cd build/release/bin/    
user@machine:~/crypto/sumokoin/build/release/bin$ ./sumo-wallet-cli 
Sumokoin 'Sapporo' (v0.2.0.0-release)
Logging at log level 0 to /home/user/crypto/sumokoin/build/release/bin/./sumo-wallet-cli.log
Specify wallet file name (e.g., MyWallet). If the wallet doesn't exist, it will be created.
Wallet file name (or Ctrl-C to quit): idh-an
Wallet and key files found, loading...
Wallet password: ***************
Opened wallet: Sumoo6NgQzzDJ2oatX9o7YgVowuUk9mCEYeh8R7MshVp55AJpck7qyjKe52ijWheLJeJity4nymirNtpZmb43cquHn3bJsDA6YH
**********************************************************************
Use "help" command to see the list of available commands.
**********************************************************************
Starting refresh...
Refresh done, blocks received: 1                                
           Account               Balance      Unlocked balance                 Label
       0 Sumoo6NgQ          22.676000000          22.676000000       Primary account
-------------------------------------------------------------------------------------
             Total          22.676000000          22.676000000
Currently selected account: [0] Primary account
Balance: 22.676000000, unlocked balance: 22.676000000
Background refresh thread started
[wallet/0 Sumoo6NgQ]: transfer Sumonzivj7i8t15YwmptcXEn9btckE2pffYXr5zACi5jCNK9toBJDByehdvD7tWyBk44swbvLixGt1WAVqicuB4o58JKtixTSo5 20
Wallet password: ***************
** No mixin value specified, default mixin 12 will be used for this transaction.
No payment id is included with this transaction. Is this okay?  (Y/Yes/N/No): Y
Segmentation fault (core dumped)
user@machine:~/crypto/sumokoin/build/release/bin$
```

Here is a list of things to consider:

- the machine has ubuntu 16.04 server as OS with all updates
- the installed packages are just those stated by the [readme](https://github.com/sumoprojects/sumokoin/blob/master/README.md)
- the daemon is running on the same machine
- there are 3 wallets. I first sent sumo from address A (1st wallet) to the 2nd wallet's address (2nd Sumoo6NgQzzDJ2oatX9o7YgVowuUk9mCEYeh8R7MshVp55AJpck7qyjKe52ijWheLJeJity4nymirNtpZmb43cquHn3bJsDA6YH); after the new balance became unlocked I tried to transfer the same amount (ignoring fees) to the 3rd wallet's address (Sumonzivj7i8t15YwmptcXEn9btckE2pffYXr5zACi5jCNK9toBJDByehdvD7tWyBk44swbvLixGt1WAVqicuB4o58JKtixTSo5). 

What happened and what can I do ?

**Comment by sumoshi** [comment]
Pls have a look at this issue @haruto-tanno 

If you don’t use subaddresses atm, you may use previous version for now. Thanks for reporting

**Comment by SadBatman** [comment]
FWIW - I started to suddenly experience crashes with the sumo-wallet-rpc daemon today. I tried to debug it and recompiled the code with -g after which it - frustratingly because I wanted to investigate with GDB -  no longer crashes but I do get:
```
2018-Feb-10 13:39:17.288687 [RPC0]amount=3.239865300, real_output=2, real_output_in_tx_index=2, indexes: 486247 698789 804906 830215 846480 846905 849423 850142 850532 850794 851488 851939 852161 
2018-Feb-10 13:39:17.288708 [RPC0]ERROR /home/x/sumokoin/src/wallet/wallet2.cpp:4006 outs.size() < out_index + 1. THROW EXCEPTION: error::wallet_internal_error
2018-Feb-10 13:39:17.288735 [RPC0]/home/x/sumokoin/src/wallet/wallet2.cpp:4006:N5tools5error21wallet_internal_errorE: outs.size() < out_index + 1
 ```

@screab-idh can you start the CLI with:

gdb ./sumo-wallet-cl

Enter 'r'

And try to replicate the issue. GDB will give more information about the crash and you can share it with us.

**Comment by screab-idh** [comment]
@SadBatman  here is the console output 

Wallet password: ***************
** No mixin value specified, default mixin 12 will be used for this transaction.
No payment id is included with this transaction. Is this okay?  (Y/Yes/N/No): Y

Thread 1 "sumo-wallet-cli" received signal SIGSEGV, Segmentation fault.
0x00000000005a706a in tools::wallet2::transfer_selected_rct(std::vector<cryptonote::tx_destination_entry, std::allocator<cryptonote::tx_destination_entry> >, std::__cxx11::list<unsigned long, std::allocator<unsigned long> >, unsigned long, std::vector<std::vector<std::tuple<unsigned long, crypto::public_key, rct::key>, std::allocator<std::tuple<unsigned long, crypto::public_key, rct::key> > >, std::allocator<std::vector<std::tuple<unsigned long, crypto::public_key, rct::key>, std::allocator<std::tuple<unsigned long, crypto::public_key, rct::key> > > > >&, unsigned long, unsigned long, std::vector<unsigned char, std::allocator<unsigned char> > const&, bool, cryptonote::transaction&, tools::wallet2::pending_tx&) ()
(gdb)

**Comment by PCFiL** [comment]
Having same, with latest git and also with pre compiled v2.0.0 bins.
please fix it, cant send anymore sumokoin from my pool.
thks

**Comment by screab-idh** [comment]
Hey guys, any news here ? Have you been able to replicate the problem or at least identify the root cause of it ?

**Comment by haruto-tanno** [comment]
This should be fixed with the latest code

**Comment by PCFiL** [comment]
@haruto-tanno ,
I confirm patch is working fine for me.
wallet seems now stable, finally  :+1:

**Comment by lukasalexander** [comment]
Just ran into this issue as well, with precompiled v0.3.0 binaries.

**Comment by sumoprojects** [comment]
-- Resolved
