### ISSUE TITLE
Cant compile from source

### ISSUE THREAD

**Issue by Warlordas** [sumoprojects/sumokoin#75]
I get this error with the latest release 

[ 80%] Linking CXX executable ../../bin/sumo-wallet-rpc
/usr/bin/ld: /tmp/cc1kJjQ7.ltrans18.ltrans.o: undefined reference to symbol 'SSL_get_verify_callback@@OPENSSL_1.0.0'
//lib/x86_64-linux-gnu/libssl.so.1.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/wallet/CMakeFiles/wallet_rpc_server.dir/build.make:127: recipe for target 'bin/sumo-wallet-rpc' failed
make[3]: *** [bin/sumo-wallet-rpc] Error 1

Any solutions?
Using this command "make CXXFLAGS="-ldl -lssl -lcrypto"" doesnt work also

**Comment by jpenner123** [comment]
try
make release-static

Works for me...so should work for you as well.

**Comment by screab-idh** [comment]
Can you give us the OS on which you are getting this error ?

**Comment by Warlordas** [comment]
Ubuntu 16.04 lts

**Comment by Warlordas** [comment]
Works with release-static. 

Thanks!

**Comment by BKdilse** [comment]
can confirm this option worked for me too.

**Comment by jpenner123** [comment]
Happy I could help you out. Greetings to sumogr.

**Comment by haruto-tanno** [comment]
This should be fixed at PR https://github.com/sumoprojects/sumokoin/pull/80

**Comment by sumoprojects** [comment]
Fixed, closed
