### ISSUE TITLE
Wallet shows 0 balance

### ISSUE THREAD

**Issue by spfoo** [sumoprojects/sumokoin#81]
I downloaded and compiled the CLI tools. Ran the daemon until it synced completely. Opened up my wallet with the client and after hours of hanging on 2 blocks it finished, but now shows a balance of 0 and no transfers. Wallet should have transfers and some coins as well.

Edit. suddenly daemon shows this:
"Last scheduled hard fork time shows a daemon update is needed now."

I'm using the latest source from git.

**Comment by sumogr** [comment]
Check that your daemon is fully synced (type status and check the current block with explorer's current block https://explorer.sumokoin.com/)
If it is fully synced
Run the command **rescan_bc** on your cli wallet prompt

Ignore that message (its a left out message from monero code, it will be cleaned)
"Last scheduled hard fork time shows a daemon update is needed now.

**Comment by quangvu3** [comment]
I think it’s wallet timestamp issue that we’ll fix soon. For now, you can restore wallet from seed words to make it work correctly

**Comment by screab-idh** [comment]
I had the same problem with the cli wallet a few months ago. I couldn't see any transfers in my cli wallet. I tried compiling the latest code, rescan_bc, reimporting keys, using the compiled released version, everything failed. The good news is that when I used the GUI wallet all the money were there.

**Comment by spfoo** [comment]
Thanks for the quick answers. Restoring with the mnemonic seed words worked out. I had even more Sumo than I remembered :-)
