### ISSUE TITLE
Change pool server

### ISSUE THREAD

**Issue by PalSec** [sumoprojects/sumokoin#86]
Hi,

I changed server for mining pool and I don`t see statistics about found block,address,etc from old pool server.
Where I will find these old data.My old server running now.
I moved lmdb from old server to new server but it didn`t  help me...

Thanks for help.

**Comment by PalSec** [comment]
I don`t use mysql...

**Comment by sumogr** [comment]
This is not the thread to open such an issue. Migrate your redis to the new server and please close this issue asap
https://stackoverflow.com/questions/6004915/how-do-i-move-a-redis-database-from-one-server-to-another

**Comment by PalSec** [comment]
Thank you very much....it is work....
