### ISSUE TITLE
New difficulty algorithm can be a trap. Warning ! Be careful devs !

### ISSUE THREAD

**Issue by bobbieltd** [sumoprojects/sumokoin#88]
I see some peoples going around to promote the “new” difficulty algo. I’m not technical enough to understand it but my instinct telling me that it is a trap. If you guys use that new diffculty algo, be careful with copyright issue.
You MUST put “Portions Copyright 2017 Masari Project” at Readme and in difficulty.cpp for just some lines of codes which I’m not sure they are effective.
In the worst case, if you are careless, they can file a DCMA to put your repo down.

**Comment by sumogr** [comment]
Dude can you please stop opening nonsense issues on Github?
I ve just checked this Masari Project and its first commit was on September 2017. Our diff algo pull was created on **June 2017** from scratch. So if they used portions of our diff algo they **MUST** put “Portions Copyright 2017 **SUMOKOIN** Project” even though we are not going to DMCA them and bring their repo down it would be nice if they did pay the appropriate credit

**Comment by bobbieltd** [comment]
I’m newbie. Yeah. Just be angried with copyright issue. So no problem here, I close the issue.

**Comment by sumogr** [comment]
No prob. In the future for any similar concerns just send an email at contact@sumokoin.org :)

**Comment by bobbieltd** [comment]
I have question. I don’t know much codes and copyright stuffs. If I used that new difficulty algo for my coin, what copyright should I put ?

Portions Copyright 2017 Sumokoin Project
Portions Copyright 2017 Masari Project

I must put both two lines, shouldn’t I ?

**Comment by bobbieltd** [comment]
All right. No more issue and no more email. Now for me anything here is non sense too. Unbelievable ! Bye !

**Comment by sumogr** [comment]
If the Masari Project improved or changed the coin in any way (I am not talking about the readme files or notices, but for actual code lines) and you are going to fork their code then indeed you should mention both. If they just copied sumokoin's code just sumokoin will do (no need to get mad)
