### ISSUE TITLE
Failed to save config to file c:\programdata\sumokoin\p2pstate.bin

### ISSUE THREAD

**Issue by hechengwine** [sumoprojects/sumokoin#89]
win64 0.2.0
when sync,the daemon outputs:Failed to save config to file c:\programdata\sumokoin\p2pstate.bin,
what should I do?
sync and wallet is ok.

**Comment by sumogr** [comment]
Its most likely a policy issue. Check your permissions of the involved folders. Modify and Write should be enabled

**Comment by sumoprojects** [comment]
-- Resolved
