### ISSUE TITLE
make debug fails

### ISSUE THREAD

**Issue by jfreeze** [sumoprojects/sumokoin#92]
Trying to debug version tags/v0.2.0.0, I get the following error:

make debug
...
[ 88%] Linking CXX executable ../../bin/sumo-wallet-rpc
libwallet.so: undefined reference to `Monero::TransactionHistoryImpl::label[abi:cxx11]() const'
libwallet.so: undefined reference to `Monero::TransactionHistoryImpl::subaddrAccount() const'
libwallet.so: undefined reference to `Monero::TransactionHistoryImpl::subaddrIndex() const'
collect2: error: ld returned 1 exit status
src/wallet/CMakeFiles/wallet_rpc_server.dir/build.make:122: recipe for target 'bin/sumo-wallet-rpc' failed
make[3]: *** [bin/sumo-wallet-rpc] Error 1
make[3]: Leaving directory '/home/jim/crypto/sumokoin/build/debug'
CMakeFiles/Makefile2:1251: recipe for target 'src/wallet/CMakeFiles/wallet_rpc_server.dir/all' failed
make[2]: *** [src/wallet/CMakeFiles/wallet_rpc_server.dir/all] Error 2
make[2]: Leaving directory '/home/jim/crypto/sumokoin/build/debug'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/jim/crypto/sumokoin/build/debug'
Makefile:36: recipe for target 'debug' failed
make: *** [debug] Error 2

**Comment by sumogr** [comment]
Yeap there are are bugs at tags/2.0, pull the latest code for debug build it should work
(on Ubuntu 16.04 for best results)

**Comment by jfreeze** [comment]
Ahh, yes. Thank you.
