### ISSUE TITLE
Sumokoin vs Monero

### ISSUE THREAD

**Issue by goktugyil** [sumoprojects/sumokoin#98]
Hello, I read your website and papers and just couldn't understand how is this project better or different than Monero?

**Comment by sumogr** [comment]
as you wish

**Comment by ZeGermanSumo** [comment]
I agree with sumogr... This is GitHub, not Bitcointalk. There is a lot of room to discuss the differences (telegram, bitcointalk, reddit ... ). Github is not the right place.

Please be so kind and close this issue. Feel free, to discuss on one of the many other channels we have.
